### ISSUE TITLE
Add adb hack to open URLs in Fx Android to dualdrive.py

### ISSUE THREAD

**Issue by hallvors** [hallvors/marionette_utils#1]
@miketaylr was going to tell me how :)

**Comment by hallvors** [comment]
(The only problem is that the script would actually become "trialdrive" when driving three browsers, and that sounds like very dubious software..)

**Comment by hallvors** [comment]
Joking aside: ping @miketaylr, I think you just need to paste some example code here and I'll take it from there :)

**Comment by miketaylr** [comment]
Thanks for the reminder...and being patient. :) Will paste some code here in a second.

**Comment by miketaylr** [comment]
So here's some code stolen from a Fennec addon build script:

``` shell
# Replace this value to push to different release channels.
# Nightly = org.mozilla.fennec
# Aurora = org.mozilla.fennec_aurora
# Beta = org.mozilla.firefox_beta
# Release = org.mozilla.firefox
ANDROID_APP_ID=org.mozilla.fennec

adb shell am start -a android.intent.action.VIEW \
                   -c android.intent.category.DEFAULT \
                   -d file:///mnt/sdcard/"$XPI" \
                   -n $ANDROID_APP_ID/.App && \
echo Pushed $XPI to $ANDROID_APP_ID
```

The `-d` is where you can pass the URI. See https://developer.android.com/intl/ru/tools/help/shell.html#IntentSpec for more on that (if you need it).

Also, `$ adb shell screencap /sdcard/blah.png` will take a screenshot of the device, if you need that.

**Comment by hallvors** [comment]
Fixed by https://github.com/hallvors/marionette_utils/commit/bb97624e854dbd2547cb6f2b555a988f39bc321c
(And as I'm considering this a personal utility of limited interest to others, development is anything but clean and tidy :-p)
